name: OICD test connectivity
on:
    workflow_dispatch:
permissions:
    contents: read
    id-token: write

jobs:
    aws_authentication:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: configure AWS creds
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                aws-region: eu-west-2
                role-session-name: Githublink
            - name: Test OIDC auth
              run: |
                  aws sts get-caller-identity
